# Generated by Django 2.1.2 on 2018-10-29 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('bought_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('edition_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('state_condition', models.CharField(choices=[('UN', 'Unknown'), ('NE', 'New'), ('LN', 'Like New'), ('VG', 'Very Good'), ('GO', 'Good'), ('AC', 'Acceptable'), ('BA', 'Bad')], default='UN', max_length=2)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='band_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Band'),
        ),
    ]
